"""
Filename: src/nocodb_py/column.py

NocoDB Column for Python
This module provides a column class to interact with NocoDB column-specific API
"""

# pylint: disable=unused-import
# pylint: disable=too-many-instance-attributes
# pylint: disable=trailing-whitespace
# pylint: disable=too-many-public-methods
# pylint: disable=line-too-long
# pylint: disable=import-outside-toplevel

import time
import threading
from typing import Dict, List, Any, Optional, Union
from enum import Enum
import requests
from .utils import parse_utc_datetime, count_of_nocodb_data
from typing import TYPE_CHECKING
if TYPE_CHECKING:
    from .table import NocoDBTable
    from .validator import ValidationLevel, ValidationResult

class NocoDBColumnType(Enum):
    """
    Enumeration of all NocoDB column types.
    
    This enum provides type-safe references to NocoDB column type identifiers.
    Used for column validation, type checking, and API interactions.
    """
    # Basic types
    SINGLE_LINE_TEXT = "SingleLineText"
    LONG_TEXT = "LongText"
    NUMBER = "Number"
    DATE = "Date"
    TIME = "Time"
    DATETIME = "DateTime"
    CHECKBOX = "Checkbox"
    YEAR = "Year"
    DECIMAL = "Decimal"
    PERCENT = "Percent"
    DURATION = "Duration"
    RATING = "Rating"
    
    # Selection types
    SINGLE_SELECT = "SingleSelect"
    MULTI_SELECT = "MultiSelect"
    
    # Validation types
    EMAIL = "Email"
    URL = "URL"
    PHONE_NUMBER = "PhoneNumber"
    CURRENCY = "Currency"
    
    # Special types
    JSON = "JSON"
    GEOMETRY = "Geometry"
    GEO_DATA = "GeoData"
    QR_CODE = "QrCode"
    BARCODE = "Barcode"
    USER = "User"
    BUTTON = "Button"
    FORMULA = "Formula"
    ATTACHMENT = "Attachment"
    
    # System & Audit types
    ID = "ID"
    ORDER = "Order"
    CREATED_TIME = "CreatedTime"
    LAST_MODIFIED_TIME = "LastModifiedTime"
    CREATED_BY = "CreatedBy"
    LAST_MODIFIED_BY = "LastModifiedBy"
    
    # Computed & Relation types
    LOOKUP = "Lookup"
    ROLLUP = "Rollup"
    LINKS = "Links"
    LINK_TO_ANOTHER_RECORD = "LinkToAnotherRecord"

    # TODO: Handle this
    FOREIGN_KEY = "ForeignKey"
    
    @classmethod
    def from_string(cls, type_str: str) -> 'NocoDBColumnType':
        """
        Convert a string to NocoDBColumnType enum.
        
        Args:
            type_str: The column type string from NocoDB API
            
        Returns:
            NocoDBColumnType: The corresponding enum value
            
        Raises:
            ValueError: If the string doesn't match any enum value
        """
        for column_type in cls:
            if column_type.value == type_str:
                return column_type
        raise ValueError(f"Unknown column type: {type_str}")

    def is_read_only(self) -> bool:
        """
        Check if the column value is inherently read-only.
        This includes system fields, audit fields, computed fields, and UI generated fields.
        
        Note: Relation fields (Links) are considered writable (via special APIs),
        so they are not included here.
        
        Returns:
            bool: True if the column type is read-only
        """
        return (
            self.is_system_managed() or
            self.is_audit() or
            self.is_computed() or
            self.is_ui_generated()
        )

    def is_system_managed(self) -> bool:
        """
        Check if the column is managed by the system (ID, Order).
        
        Returns:
            bool: True if system managed
        """
        return self in {
            NocoDBColumnType.ID,
            NocoDBColumnType.ORDER
        }

    def is_audit(self) -> bool:
        """
        Check if the column is an audit field (CreatedTime, LastModifiedTime, etc.).
        
        Returns:
            bool: True if audit field
        """
        return self in {
            NocoDBColumnType.CREATED_TIME,
            NocoDBColumnType.LAST_MODIFIED_TIME,
            NocoDBColumnType.CREATED_BY,
            NocoDBColumnType.LAST_MODIFIED_BY
        }

    def is_computed(self) -> bool:
        """
        Check if the column is a computed field (Formula, Lookup, Rollup).
        
        Returns:
            bool: True if computed field
        """
        return self in {
            NocoDBColumnType.FORMULA,
            NocoDBColumnType.LOOKUP,
            NocoDBColumnType.ROLLUP
        }
        
    def is_ui_generated(self) -> bool:
        """
        Check if the column is generated by UI (QrCode, Barcode, Button).
        
        Returns:
            bool: True if UI generated
        """
        return self in {
            NocoDBColumnType.QR_CODE,
            NocoDBColumnType.BARCODE,
            NocoDBColumnType.BUTTON
        }

    def is_relation(self) -> bool:
        """
        Check if the column is a relation field (Links, LinkToAnotherRecord).
        
        Returns:
            bool: True if relation field
        """
        return self in {
            NocoDBColumnType.LINKS,
            NocoDBColumnType.LINK_TO_ANOTHER_RECORD
        }


# pylint: disable=too-many-instance-attributes
class NocoDBColumn:
    """
    A class representing a NocoDB column with column-specific operations
    
    Attributes:
        _table ('NocoDBTable'): The NocoDB table instance
        _column_id (str): The unique column identifier
    """

    def __init__(self, table: 'NocoDBTable', column_id: str, timeout: int = 30, cache_ttl: Optional[int] = 300):
        """
        Initialize the NocoDBColumn with table and column ID
        
        Args:
            table ('NocoDBTable'): The NocoDB table instance
            column_id (str): The unique column identifier
            timeout (int): Request timeout in seconds
            cache_ttl (Optional[int]): Cache time-to-live in seconds
        """
        self._table = table
        self._column_id = column_id
        self._timeout = timeout
        self._cache_ttl = cache_ttl

        # Column-specific cache
        self._column_info_cache = None
        self._column_info_timestamp = 0
        self._cache_lock = threading.RLock()

    def __str__(self) -> str:
        """
        String representation of the NocoDBColumn
        
        Returns:
            str: String representation of the column
        """
        return f"NocoDBColumn(id='{self._column_id}', table={self._table})"

    def __repr__(self) -> str:
        """
        Official string representation of the NocoDBColumn
        
        Returns:
            str: Official representation of the column
        """
        return self.__str__()

    def __eq__(self, other: object) -> bool:
        """
        Check equality with another NocoDBColumn
        
        Args:
            other (object): The other object to compare with
            
        Returns:
            bool: True if equal, False otherwise
        """
        if not isinstance(other, NocoDBColumn):
            return False
        return self._column_id == other._column_id and self._table == other._table

    def __hash__(self) -> int:
        """
        Hash implementation for NocoDBColumn.
        
        Returns:
            int: Hash value based on immutable attributes that define identity
        """
        return hash((self._table, self._column_id))

    @property
    def column_id(self) -> str:
        """
        Get the column ID
        
        Returns:
            str: The column ID
        """
        return self._column_id
    
    def get_column_id(self) -> str:
        """
        Get the column ID (compatibility method)
        
        Returns:
            str: The column ID
        """
        return self.column_id
    
    get_id = get_column_id

    @property
    def table(self) -> 'NocoDBTable':
        """
        Get the table instance
        
        Returns:
            'NocoDBTable': The table instance
        """
        return self._table
    
    def get_table(self) -> 'NocoDBTable':
        """
        Get the table instance (compatibility method)
        
        Returns:
            'NocoDBTable': The table instance
        """
        return self.table

    def get_meta_v2_prefix(self) -> str:
        """
        Get the meta v2 prefix
        
        Returns:
            str: The meta v2 prefix
        """
        return f"/api/v2/meta/columns/{self._column_id}"


    def get_full_info(self, force_refresh: bool = False) -> Dict:
        """
        Get the full info for the column
        
        Args:
            force_refresh (bool): Whether to force a refresh of the column info
            
        Returns:
            Dict: The full column info
        """
        with self._cache_lock:
            current_time = time.time()
            cache_ttl = self._cache_ttl
            if(not force_refresh and
               self._column_info_cache is not None and
               (cache_ttl is None or current_time - self._column_info_timestamp < cache_ttl)
               ):
                return self._column_info_cache

            # pylint: disable=protected-access
            # Reason: NocoDBClient._get is intentionally accessible to NocoDB-related classes
            self._column_info_cache = self._table.get_project().client._get(
                f"{self.get_meta_v2_prefix()}"
            )
            self._column_info_timestamp = current_time
            return self._column_info_cache

    def get_column_type(self, force_refresh: bool = False) -> NocoDBColumnType:
        """
        Get the column type as a NocoDBColumnType enum.
        
        This method encapsulates the core logic of converting the column's
        type string from the API to a type-safe enum value.
        
        Args:
            force_refresh (bool): Whether to force a refresh of the column info
            
        Returns:
            NocoDBColumnType: The column type as an enum value
            
        Raises:
            ValueError: If the column type is unknown
            requests.exceptions.RequestException: If API request fails
        """
        column_info = self.get_full_info(force_refresh=force_refresh)
        type_string = column_info.get('uidt', '')
        
        try:
            return NocoDBColumnType.from_string(type_string)
        except ValueError as e:
            raise ValueError(f"Unknown column type '{type_string}' for column '{self._column_id}': {e}") from e

    def clear_column_info_cache(self):
        """
        Clear column info cache
        """
        with self._cache_lock:
            self._column_info_cache = None
            self._column_info_timestamp = 0

    def verify_data(self, value: Any, level: Optional['ValidationLevel'] = None) -> 'ValidationResult':
        """
        Verify if the given value is valid for this column.
        
        Args:
            value: The value to verify
            level: Validation level (STRUCTURAL or FULL), defaults to STRUCTURAL
            
        Returns:
            ValidationResult: Detailed validation result with error message and converted value
        """
        from .validator import validate_value, ValidationLevel
        
        if level is None:
            level = ValidationLevel.STRUCTURAL
        
        column_type = self.get_column_type()
        return validate_value(value, column_type, self, level)


class NocoDBSchema:
    """
    NocoDB Table Schema for Python
    
    This class represents the schema (structure) of a NocoDB table, providing
    column metadata and validation rules for record operations.
    
    Attributes:
        table ('NocoDBTable'): The NocoDB table instance
        _columns_info (List[Dict]): List of column information
        _columns_by_title (Dict[str, Dict]): Column info indexed by title
        _columns_by_id (Dict[str, Dict]): Column info indexed by ID
        _writable_columns (List[Dict]): List of writable columns
        _readonly_columns (List[Dict]): List of read-only columns
        _system_columns (List[Dict]): List of system columns
    """
    
    def __init__(self, table: 'NocoDBTable'):
        """
        Initialize the NocoDBSchema with a table instance
        
        Args:
            table ('NocoDBTable'): The NocoDB table instance
        """
        self.table = table
        self._columns_info = None
        self._columns_by_title = None
        self._columns_by_id = None
        self._writable_columns = None
        self._readonly_columns = None
        self._system_columns = None
    
    def load_schema(self, force_refresh: bool = False) -> None:
        """
        Load the table schema information
        
        Args:
            force_refresh (bool): Whether to force a refresh of the schema cache
        """
        columns_info = self.table.get_columns_full_info(force_refresh)
        self._columns_info = columns_info
        
        # Build indexes for efficient lookup
        self._columns_by_title = {col.get('title'): col for col in columns_info}
        self._columns_by_id = {col.get('id'): col for col in columns_info}
        
        # Classify columns by their properties
        self._writable_columns = []
        self._readonly_columns = []
        self._system_columns = []
        
        for col in columns_info:
            if col.get('system') == 1:
                self._system_columns.append(col)
            elif col.get('readonly') == 1:
                self._readonly_columns.append(col)
            else:
                self._writable_columns.append(col)
    
    def get_column_by_title(self, title: str) -> Optional[Dict]:
        """
        Get column information by column title
        
        Args:
            title (str): The column title to look up
            
        Returns:
            Optional[Dict]: Column information dictionary, or None if not found
        """
        if self._columns_by_title is None:
            self.load_schema()
        return self._columns_by_title.get(title) if self._columns_by_title else None
    
    def get_column_by_id(self, column_id: str) -> Optional[Dict]:
        """
        Get column information by column ID
        
        Args:
            column_id (str): The column ID to look up
            
        Returns:
            Optional[Dict]: Column information dictionary, or None if not found
        """
        if self._columns_by_id is None:
            self.load_schema()
        return self._columns_by_id.get(column_id) if self._columns_by_id else None
    
    def is_writable_field(self, field_name: str) -> bool:
        """
        Check if a field is writable (not system or read-only)
        
        Args:
            field_name (str): The field name to check
            
        Returns:
            bool: True if the field is writable, False otherwise
        """
        col_info = self.get_column_by_title(field_name)
        if not col_info:
            return False
        return col_info.get('system', 0) == 0 and col_info.get('readonly', 0) == 0
    
    @property
    def writable_fields(self) -> List[str]:
        """
        Get all writable field titles
        
        Returns:
            List[str]: List of writable field titles
        """
        if self._writable_columns is None:
            self.load_schema()
        return [col.get('title') for col in self._writable_columns] if self._writable_columns else []
    
    @property
    def system_fields(self) -> List[str]:
        """
        Get all system field titles
        
        Returns:
            List[str]: List of system field titles
        """
        if self._system_columns is None:
            self.load_schema()
        return [col.get('title') for col in self._system_columns] if self._system_columns else []
    
    @property
    def readonly_fields(self) -> List[str]:
        """
        Get all read-only field titles
        
        Returns:
            List[str]: List of read-only field titles
        """
        if self._readonly_columns is None:
            self.load_schema()
        return [col.get('title') for col in self._readonly_columns] if self._readonly_columns else []
    
    @property
    def all_fields(self) -> List[str]:
        """
        Get all field titles
        
        Returns:
            List[str]: List of all field titles
        """
        if self._columns_by_title is None:
            self.load_schema()
        return list(self._columns_by_title.keys()) if self._columns_by_title else []
    
    def __str__(self) -> str:
        """String representation of the schema"""
        field_count = len(self._columns_by_title) if self._columns_by_title else 0
        return f"NocoDBSchema(table={self.table}, fields={field_count})"
    
    def __repr__(self) -> str:
        """Official string representation"""
        return self.__str__()
