"""
Filename: src/nocodb_py/column.py

NocoDB Column for Python
This module provides a column class to interact with NocoDB column-specific API
"""

# pylint: disable=unused-import
# pylint: disable=too-many-instance-attributes
# pylint: disable=trailing-whitespace
# pylint: disable=too-many-public-methods
# pylint: disable=line-too-long
# pylint: disable=import-outside-toplevel

import time
import threading
from typing import Dict, List, Any, Optional, Union
from enum import Enum
import requests
from .utils import parse_utc_datetime, count_of_nocodb_data
from typing import TYPE_CHECKING
if TYPE_CHECKING:
    from .table import NocoDBTable
    from .validator import ValidationLevel, ValidationResult

class NocoDBColumnType(Enum):
    """
    Enumeration of all NocoDB column types.
    
    This enum provides type-safe references to NocoDB column type identifiers.
    Used for column validation, type checking, and API interactions.
    """
    # Basic types
    SINGLE_LINE_TEXT = "SingleLineText"
    LONG_TEXT = "LongText"
    NUMBER = "Number"
    DATE = "Date"
    TIME = "Time"
    DATETIME = "DateTime"
    CHECKBOX = "Checkbox"
    YEAR = "Year"
    DECIMAL = "Decimal"
    PERCENT = "Percent"
    DURATION = "Duration"
    RATING = "Rating"
    
    # Selection types
    SINGLE_SELECT = "SingleSelect"
    MULTI_SELECT = "MultiSelect"
    
    # Validation types
    EMAIL = "Email"
    URL = "URL"
    PHONE_NUMBER = "PhoneNumber"
    CURRENCY = "Currency"
    
    # Special types
    JSON = "JSON"
    GEOMETRY = "Geometry"
    GEO_DATA = "GeoData"
    QR_CODE = "QrCode"
    BARCODE = "Barcode"
    USER = "User"
    BUTTON = "Button"
    FORMULA = "Formula"
    ATTACHMENT = "Attachment"
    
    # System & Audit types
    ID = "ID"
    ORDER = "Order"
    CREATED_TIME = "CreatedTime"
    LAST_MODIFIED_TIME = "LastModifiedTime"
    CREATED_BY = "CreatedBy"
    LAST_MODIFIED_BY = "LastModifiedBy"
    
    # Computed & Relation types
    LOOKUP = "Lookup"
    ROLLUP = "Rollup"
    LINKS = "Links"
    LINK_TO_ANOTHER_RECORD = "LinkToAnotherRecord"

    #pylint: disable=fixme
    # TODO: Handle this
    FOREIGN_KEY = "ForeignKey"
    
    @classmethod
    def from_string(cls, type_str: str) -> 'NocoDBColumnType':
        """
        Convert a string to NocoDBColumnType enum.
        
        Args:
            type_str: The column type string from NocoDB API
            
        Returns:
            NocoDBColumnType: The corresponding enum value
            
        Raises:
            ValueError: If the string doesn't match any enum value
        """
        for column_type in cls:
            if column_type.value == type_str:
                return column_type
        raise ValueError(f"Unknown column type: {type_str}")

    def is_read_only(self) -> bool:
        """
        Check if the column value is inherently read-only.
        This includes system fields, audit fields, computed fields, and UI generated fields.
        
        Note: Relation fields (Links) are considered writable (via special APIs),
        so they are not included here.
        
        Returns:
            bool: True if the column type is read-only
        """
        return (
            self.is_system_managed() or
            self.is_audit() or
            self.is_computed() or
            self.is_ui_generated()
        )

    def is_system_managed(self) -> bool:
        """
        Check if the column is managed by the system (ID, Order).
        
        Returns:
            bool: True if system managed
        """
        return self in {
            NocoDBColumnType.ID,
            NocoDBColumnType.ORDER
        }

    def is_audit(self) -> bool:
        """
        Check if the column is an audit field (CreatedTime, LastModifiedTime, etc.).
        
        Returns:
            bool: True if audit field
        """
        return self in {
            NocoDBColumnType.CREATED_TIME,
            NocoDBColumnType.LAST_MODIFIED_TIME,
            NocoDBColumnType.CREATED_BY,
            NocoDBColumnType.LAST_MODIFIED_BY
        }

    def is_computed(self) -> bool:
        """
        Check if the column is a computed field (Formula, Lookup, Rollup).
        
        Returns:
            bool: True if computed field
        """
        return self in {
            NocoDBColumnType.FORMULA,
            NocoDBColumnType.LOOKUP,
            NocoDBColumnType.ROLLUP
        }
        
    def is_ui_generated(self) -> bool:
        """
        Check if the column is generated by UI (QrCode, Barcode, Button).
        
        Returns:
            bool: True if UI generated
        """
        return self in {
            NocoDBColumnType.QR_CODE,
            NocoDBColumnType.BARCODE,
            NocoDBColumnType.BUTTON
        }

    def is_relation(self) -> bool:
        """
        Check if the column is a relation field (Links, LinkToAnotherRecord).
        
        Returns:
            bool: True if relation field
        """
        return self in {
            NocoDBColumnType.LINKS,
            NocoDBColumnType.LINK_TO_ANOTHER_RECORD
        }

    def is_basic(self) -> bool:
        """
        Check if the column type is basic (writable, simple structure, independent).
        
        Basic column types are:
        - Writable (not read-only)
        - Simple structure (no nested data)
        - Independent (not dependent on other columns/tables)
        - Can be modified independently
        
        Returns:
            bool: True if the column type is basic
        """
        basic_types = {
            # Basic types
            NocoDBColumnType.SINGLE_LINE_TEXT,
            NocoDBColumnType.LONG_TEXT,
            NocoDBColumnType.NUMBER,
            NocoDBColumnType.DATE,
            NocoDBColumnType.TIME,
            NocoDBColumnType.DATETIME,
            NocoDBColumnType.CHECKBOX,
            NocoDBColumnType.YEAR,
            NocoDBColumnType.DECIMAL,
            NocoDBColumnType.PERCENT,
            NocoDBColumnType.DURATION,
            NocoDBColumnType.RATING,
            
            # Selection types
            NocoDBColumnType.SINGLE_SELECT,
            NocoDBColumnType.MULTI_SELECT,
            
            # Validation types
            NocoDBColumnType.EMAIL,
            NocoDBColumnType.URL,
            NocoDBColumnType.PHONE_NUMBER,
            NocoDBColumnType.CURRENCY,
        }
        return self in basic_types


# pylint: disable=too-many-instance-attributes
class NocoDBColumn:
    """
    A class representing a NocoDB column with column-specific operations
    
    Attributes:
        _table ('NocoDBTable'): The NocoDB table instance
        _column_id (str): The unique column identifier
    """

    def __init__(self, table: 'NocoDBTable', column_id: str, timeout: int = 30, cache_ttl: Optional[int] = 300):
        """
        Initialize the NocoDBColumn with table and column ID
        
        Args:
            table ('NocoDBTable'): The NocoDB table instance
            column_id (str): The unique column identifier
            timeout (int): Request timeout in seconds
            cache_ttl (Optional[int]): Cache time-to-live in seconds
        """
        self._table = table
        self._column_id = column_id
        self._timeout = timeout
        self._cache_ttl = cache_ttl

        # Column-specific cache
        self._column_info_cache = None
        self._column_info_timestamp = 0
        self._cache_lock = threading.RLock()

    def __str__(self) -> str:
        """
        String representation of the NocoDBColumn
        
        Returns:
            str: String representation of the column
        """
        return f"NocoDBColumn(id='{self._column_id}', table={self._table})"

    def __repr__(self) -> str:
        """
        Official string representation of the NocoDBColumn
        
        Returns:
            str: Official representation of the column
        """
        return self.__str__()

    def __eq__(self, other: object) -> bool:
        """
        Check equality with another NocoDBColumn
        
        Args:
            other (object): The other object to compare with
            
        Returns:
            bool: True if equal, False otherwise
        """
        if not isinstance(other, NocoDBColumn):
            return False
        return self._column_id == other._column_id and self._table == other._table

    def __hash__(self) -> int:
        """
        Hash implementation for NocoDBColumn.
        
        Returns:
            int: Hash value based on immutable attributes that define identity
        """
        return hash((self._table, self._column_id))

    @property
    def column_id(self) -> str:
        """
        Get the column ID
        
        Returns:
            str: The column ID
        """
        return self._column_id
    
    def get_column_id(self) -> str:
        """
        Get the column ID (compatibility method)
        
        Returns:
            str: The column ID
        """
        return self.column_id
    
    get_id = get_column_id

    @property
    def table(self) -> 'NocoDBTable':
        """
        Get the table instance
        
        Returns:
            'NocoDBTable': The table instance
        """
        return self._table
    
    def get_table(self) -> 'NocoDBTable':
        """
        Get the table instance (compatibility method)
        
        Returns:
            'NocoDBTable': The table instance
        """
        return self.table

    def get_meta_v2_prefix(self) -> str:
        """
        Get the meta v2 prefix
        
        Returns:
            str: The meta v2 prefix
        """
        return f"/api/v2/meta/columns/{self._column_id}"


    def get_full_info(self, force_refresh: bool = False) -> Dict:
        """
        Get the full info for the column
        
        Args:
            force_refresh (bool): Whether to force a refresh of the column info
            
        Returns:
            Dict: The full column info
        """
        with self._cache_lock:
            current_time = time.time()
            cache_ttl = self._cache_ttl
            if(not force_refresh and
               self._column_info_cache is not None and
               (cache_ttl is None or current_time - self._column_info_timestamp < cache_ttl)
               ):
                return self._column_info_cache

            # pylint: disable=protected-access
            # Reason: NocoDBClient._get is intentionally accessible to NocoDB-related classes
            self._column_info_cache = self._table.get_project().client._get(
                f"{self.get_meta_v2_prefix()}"
            )
            self._column_info_timestamp = current_time
            return self._column_info_cache

    def get_column_type(self, force_refresh: bool = False) -> NocoDBColumnType:
        """
        Get the column type as a NocoDBColumnType enum.
        
        This method encapsulates the core logic of converting the column's
        type string from the API to a type-safe enum value.
        
        Args:
            force_refresh (bool): Whether to force a refresh of the column info
            
        Returns:
            NocoDBColumnType: The column type as an enum value
            
        Raises:
            ValueError: If the column type is unknown
            requests.exceptions.RequestException: If API request fails
        """
        column_info = self.get_full_info(force_refresh=force_refresh)
        type_string = column_info.get('uidt', '')
        
        try:
            return NocoDBColumnType.from_string(type_string)
        except ValueError as e:
            raise ValueError(f"Unknown column type '{type_string}' for column '{self._column_id}': {e}") from e

    def clear_column_info_cache(self):
        """
        Clear column info cache
        """
        with self._cache_lock:
            self._column_info_cache = None
            self._column_info_timestamp = 0

    def verify_data(self, value: Any, level: Optional['ValidationLevel'] = None) -> 'ValidationResult':
        """
        Verify if the given value is valid for this column.
        
        Args:
            value: The value to verify
            level: Validation level (STRUCTURAL or FULL), defaults to STRUCTURAL
            
        Returns:
            ValidationResult: Detailed validation result with error message and converted value
        """
        from .validator import validate_value, ValidationLevel
        
        if level is None:
            level = ValidationLevel.STRUCTURAL
        
        column_type = self.get_column_type()
        return validate_value(value, column_type, self, level)


class NocoDBSchema:
    """
    NocoDB Table Schema for Python
    
    This class represents the schema (structure) of a NocoDB table, providing
    column metadata and validation rules for record operations.
    
    Supports two states: online (attached to table) and offline (local schema definition).
    
    Attributes:
        table (Optional['NocoDBTable']): The NocoDB table instance, None for offline schema
        _column_types_by_title (Dict[str, NocoDBColumnType]): Column types indexed by title
        _column_types_by_id (Dict[str, NocoDBColumnType]): Column types indexed by ID (attached state only)
    """
    
    def __init__(self, table: Optional['NocoDBTable'] = None):
        """
        Initialize the NocoDBSchema with an optional table instance
        
        Args:
            table (Optional['NocoDBTable']): The NocoDB table instance, None for offline schema
        """
        self.table = table
        self._column_types_by_title: Dict[str, NocoDBColumnType] = {}  # Used for both online and offline states
        self._column_types_by_id: Optional[Dict[str, NocoDBColumnType]] = None   # Only used in attached state
    
    @property
    def is_attached(self) -> bool:
        """Whether the schema is attached to a NocoDB table"""
        return self.table is not None
    
    @property
    def is_detached(self) -> bool:
        """Whether the schema is offline (detached)"""
        return not self.is_attached
    
    def attach(self, table: 'NocoDBTable') -> None:
        """
        Attach offline schema to a table (one-time operation)
        
        Args:
            table: Table object to attach to
            
        Raises:
            RuntimeError: If schema is already attached
        """
        if self.is_attached:
            raise RuntimeError("Schema is already attached to a table")
        self.table = table
        # Execute schema synchronization
        self._sync_with_table()
    
    def load_schema(self, force_refresh: bool = False, table: Optional['NocoDBTable'] = None) -> None:
        """
        Load the table schema information
        
        Args:
            force_refresh (bool): Whether to force a refresh of the schema cache
            table (Optional['NocoDBTable']): Optional table object for attach operation
            
        Raises:
            RuntimeError: If trying to attach to already attached schema
        """
        # Attach operation (one-time)
        if table is not None and self.is_detached:
            self.attach(table)
            return
        
        if self.is_attached:
            if self.table is not None:  # Type safety check
                columns_info = self.table.get_columns_full_info(force_refresh)
                self._columns_info = columns_info
                
                # Build indexes for efficient lookup
                self._columns_by_title = {col.get('title'): col for col in columns_info}
                self._columns_by_id = {col.get('id'): col for col in columns_info}
                
                # Build column type mappings
                self._column_types_by_title = {}
                self._column_types_by_id = {}
                
                for col in columns_info:
                    title = col.get('title')
                    column_id = col.get('id')
                    type_string = col.get('uidt', '')
                    
                    if title and column_id and type_string:
                        try:
                            column_type = NocoDBColumnType.from_string(type_string)
                            self._column_types_by_title[title] = column_type
                            self._column_types_by_id[column_id] = column_type
                        except ValueError:
                            # Skip columns with unknown types
                            continue
        else:
            # Offline state: build schema from offline columns
            self._build_offline_schema()
    
    def _build_offline_schema(self) -> None:
        """Build schema indexes from offline column definitions"""
        # For offline schema, we only need to ensure _column_types_by_title is populated
        # _column_types_by_id remains None in offline state
        self._column_types_by_id = None
    
    def _sync_with_table(self) -> None:
        """
        Synchronize offline schema with table schema
        
        Handles conflicts and mismatches between offline and table columns.
        """
        if not self.is_attached or self.table is None:
            return
        
        # Load table schema
        table_columns_info = self.table.get_columns_full_info()
        table_columns_by_title = {col.get('title'): col for col in table_columns_info}
        
        # Conflict handling
        for title, offline_type in list(self._column_types_by_title.items()):
            if title and title in table_columns_by_title:  # Ensure title is not None
                table_col = table_columns_by_title[title]
                table_type = NocoDBColumnType.from_string(table_col.get('uidt', ''))
                
                if table_type == offline_type:
                    # Type match: assign column ID naturally
                    pass  # Natural handling
                else:
                    # Type mismatch: warn and force type change
                    import warnings
                    warnings.warn(
                        f"Column '{title}' type mismatch: offline={offline_type}, table={table_type}. "
                        f"Using table type.",
                        UserWarning
                    )
                    # Force using table type
                    self._column_types_by_title[title] = table_type
            elif title:  # Only process if title is not None
                # Offline exists but table doesn't: warn and remove
                import warnings
                warnings.warn(
                    f"Column '{title}' exists in offline schema but not in table. Removing from schema.",
                    UserWarning
                )
                del self._column_types_by_title[title]
        
        # Handle columns that exist in table but not in offline schema
        for title, table_col in table_columns_by_title.items():
            if title and title not in self._column_types_by_title:  # Ensure title is not None
                # Create this column
                table_type = NocoDBColumnType.from_string(table_col.get('uidt', ''))
                self._column_types_by_title[title] = table_type
        
        # Rebuild schema after synchronization
        self._build_offline_schema()
    
    def add_column(self, title: str, column_type: NocoDBColumnType) -> None:
        """
        Add a column to offline schema (basic types only)
        
        Args:
            title (str): Column title
            column_type (NocoDBColumnType): Column type (must be basic)
            
        Raises:
            RuntimeError: If schema is attached
            ValueError: If column type is not basic
        """
        if not self.is_detached:
            raise RuntimeError("Cannot add columns to attached schema")
        if not column_type.is_basic():
            raise ValueError("Only basic column types can be added to offline schema")
        self._column_types_by_title[title] = column_type
    
    def remove_column(self, title: str) -> None:
        """
        Remove a column from offline schema
        
        Args:
            title (str): Column title to remove
            
        Raises:
            RuntimeError: If schema is attached
            KeyError: If column not found
        """
        if not self.is_detached:
            raise RuntimeError("Cannot remove columns from attached schema")
        if title not in self._column_types_by_title:
            raise KeyError(f"Column '{title}' not found")
        del self._column_types_by_title[title]
    
    def update_column(self, title: str, new_type: NocoDBColumnType) -> None:
        """
        Update column type in offline schema
        
        Args:
            title (str): Column title
            new_type (NocoDBColumnType): New column type (must be basic)
            
        Raises:
            RuntimeError: If schema is attached
            KeyError: If column not found
            ValueError: If column type is not basic
        """
        if not self.is_detached:
            raise RuntimeError("Cannot update columns in attached schema")
        if title not in self._column_types_by_title:
            raise KeyError(f"Column '{title}' not found")
        if not new_type.is_basic():
            raise ValueError("Only basic column types can be used in offline schema")
        self._column_types_by_title[title] = new_type
    
    def get_column_by_title(self, title: str) -> Optional[Dict]:
        """
        Get column information by column title
        
        Args:
            title (str): The column title to look up
            
        Returns:
            Optional[Dict]: Column information dictionary, or None if not found
        """
        if self._columns_by_title is None:
            self.load_schema()
        return self._columns_by_title.get(title) if self._columns_by_title else None
    
    def get_column_by_id(self, column_id: str) -> Optional[Dict]:
        """
        Get column information by column ID
        
        Args:
            column_id (str): The column ID to look up
            
        Returns:
            Optional[Dict]: Column information dictionary, or None if not found
        """
        if self._columns_by_id is None:
            self.load_schema()
        return self._columns_by_id.get(column_id) if self._columns_by_id else None
    
    def get_column_type_by_title(self, title: str) -> Optional[NocoDBColumnType]:
        """
        Get column type by column title
        
        Args:
            title (str): The column title to look up
            
        Returns:
            Optional[NocoDBColumnType]: Column type, or None if not found
        """
        if self._column_types_by_title is None:
            self.load_schema()
        return self._column_types_by_title.get(title) if self._column_types_by_title else None
    
    def get_column_type_by_id(self, column_id: str) -> Optional[NocoDBColumnType]:
        """
        Get column type by column ID
        
        Args:
            column_id (str): The column ID to look up
            
        Returns:
            Optional[NocoDBColumnType]: Column type, or None if not found
        """
        if self._column_types_by_id is None:
            self.load_schema()
        return self._column_types_by_id.get(column_id) if self._column_types_by_id else None
    
    def is_writable_field(self, field_name: str) -> bool:
        """
        Check if a field is writable (not system or read-only)
        
        Args:
            field_name (str): The field name to check
            
        Returns:
            bool: True if the field is writable, False otherwise
        """
        column_type = self.get_column_type_by_title(field_name)
        if not column_type:
            return False
        return not column_type.is_read_only()
    
    @property
    def writable_fields(self) -> List[str]:
        """
        Get all writable field titles
        
        Returns:
            List[str]: List of writable field titles
        """
        if not self._column_types_by_title:
            self.load_schema()
        
        writable = []
        for title, column_type in self._column_types_by_title.items():
            if title and not column_type.is_read_only():
                writable.append(title)
        return writable
    
    @property
    def system_fields(self) -> List[str]:
        """
        Get all system field titles
        
        Returns:
            List[str]: List of system field titles
        """
        if not self._column_types_by_title:
            self.load_schema()
        
        system_fields = []
        for title, column_type in self._column_types_by_title.items():
            if title and column_type.is_system_managed():
                system_fields.append(title)
        return system_fields
    
    @property
    def readonly_fields(self) -> List[str]:
        """
        Get all read-only field titles
        
        Returns:
            List[str]: List of read-only field titles
        """
        if not self._column_types_by_title:
            self.load_schema()
        
        readonly = []
        for title, column_type in self._column_types_by_title.items():
            if title and column_type.is_read_only():
                readonly.append(title)
        return readonly
    
    @property
    def all_fields(self) -> List[str]:
        """
        Get all field titles
        
        Returns:
            List[str]: List of all field titles
        """
        if not self._column_types_by_title:
            self.load_schema()
        # Ensure we only return string keys
        return [str(key) for key in self._column_types_by_title.keys() if key is not None]
    
    @property
    def offline_columns(self) -> Dict[str, NocoDBColumnType]:
        """
        Get all offline column definitions (detached state only)
        
        Returns:
            Dict[str, NocoDBColumnType]: Mapping of column titles to types
        """
        if not self.is_detached:
            raise RuntimeError("Offline columns are only available in detached state")
        return self._column_types_by_title.copy()
    
    def __str__(self) -> str:
        """String representation of the schema"""
        if self.is_attached:
            field_count = len(self._column_types_by_title) if self._column_types_by_title else 0
            return f"NocoDBSchema(table={self.table}, fields={field_count}, attached)"
        else:
            field_count = len(self._column_types_by_title)
            return f"NocoDBSchema(offline_fields={field_count}, detached)"
    
    def __repr__(self) -> str:
        """Official string representation"""
        return self.__str__()
